### ISSUE TITLE
BLAT Alignment: Error when initializing QueryHandler

### ISSUE THREAD

**Issue by samriddhi99** [samriddhi99/dcd_mapping#1]
Hi,
While working on the get_gene_data function: 

```
from gene.query import QueryHandler
def get_gene_data(i, blat_chr, return_chr):
    qh = QueryHandler()
    try:
        uniprot = dat.at[i,'uniprot_id']
        gsymb = qh.normalize(str(f'uniprot:{uniprot}')).gene_descriptor.label
    except:
        try:
            target = dat.at[i, 'target'].split(' ')[0]
            gsymb = qh.normalize(target).gene_descriptor.label
        except:
            return 'NA' # if gsymb cannot be extracted
   
    temp = qh.search(gsymb).source_matches
    source_dict = {}
    for i in range(len(temp)):
        source_dict[temp[i].source] = i
    
    if 'HGNC' in source_dict and return_chr == True:
        chrom = temp[source_dict['HGNC']].records[0].locations[0].chr
        return chrom
    
    if 'Ensembl' in source_dict and return_chr == False and len(temp[source_dict['Ensembl']].records) != 0:
        for j in range(len(temp[source_dict['Ensembl']].records)):
            for k in range(len(temp[source_dict['Ensembl']].records[j].locations)):
                if temp[source_dict['Ensembl']].records[j].locations[k].interval.type == 'SequenceInterval': # Multiple records per source
                    start = temp[source_dict['Ensembl']].records[j].locations[k].interval.start.value
                    end = temp[source_dict['Ensembl']].records[j].locations[k].interval.end.value
                    loc_list = {}
                    loc_list['start'] = start
                    loc_list['end'] = end
                    return loc_list
    if 'NCBI' in source_dict and return_chr == False and len(temp[source_dict['NCBI']].records) != 0:
        for j in range(len(temp[source_dict['NCBI']].records)):
            for k in range(len(temp[source_dict['NCBI']].records[j].locations)):
                if temp[source_dict['NCBI']].records[j].locations[k].interval.type == 'SequenceInterval':
                    start = temp[source_dict['NCBI']].records[j].locations[k].interval.start.value
                    end = temp[source_dict['NCBI']].records[j].locations[k].interval.end.value
                    loc_list = {}
                    loc_list['start'] = start
                    loc_list['end'] = end
                    return loc_list
    return 'NA'    

```

this is how it runs in the notebooks.

I create the object `qh = QueryHandler()`
While running it on python if I do this I get the error: 
`TypeError: QueryHandler.__init__() missing 1 required positional argument: 'database'`

So I had to pass an arguement of type AbstractDatabase through it

For that I had to create another class which inherits from AbstractDatabase and does nothing but has all the functions of AbstractDatabase, and then create an object of that class. 

```
#class_for_qh
from gene.database import AbstractDatabase
class ConcreteClass(AbstractDatabase):
    def __init__(self):
        pass

    def list_tables(self):
        pass

    def _check_delete_okay(self):
        pass

    def drop_db(self):
        pass

    def initialize_db(self):
        pass

    def get_source_metadata(self):
        pass

    def get_record_by_id(self):
        pass

    def get_refs_by_type(self):
        pass

    def get_all_concept_ids(self):
        pass

    def add_source_metadata(self):
        pass

    def add_record(self):
        pass

    def add_merged_record(self):
        pass

    def update_merge_ref(self):
        pass

    def delete_normalized_concepts(self):
        pass

    def delete_source(self):
        pass

    def complete_write_transaction(self):
        pass

    def close_connection(self):
        pass
```

And the way to remove the error was to put an object of this newly created class. 
```
from class_for_qh import ConcreteClass
abstract_database_obj = ConcreteClass()
qh = QueryHandler(abstract_database_obj)
```
This makes the code work but I feel like this isn't a very good method to solve this problem.

**Comment by jsstevenson** [comment]
Hi, just saw this from the GA4GH slack channel. This is a great question, and reflects a recent update to the gene normalizer API. You're correct that you want to pass a database object of some kind to the query handler class. The easiest way to do this is to call the `create_db` function from the `gene.database` module:

```python
from gene.query import QueryHandler
from gene.database import create_db
q = QueryHandler(create_db())
result = q.normalize("BRAF")
print(result.gene_descriptor.alternate_labels) # should print something like: ['NS7', 'RAFB1', 'B-raf', 'BRAF-1', 'BRAF1', 'B-RAF1']
```

`create_db`, when called with no arguments, will try to create a database interface that connects to a DynamoDB process being served at `localhost:8000` (under the hood, this is basically the same behavior as you used to see if you created `QueryHandler` with no arguments). You can provide a URL argument to the function, or set some environment variables, if the DB is being served at a different location, or if you want to use a different database implementation (we also provide one for PostgreSQL, but you could also write an interface to a different kind of data source). 

I'm still working on standing up a final version of the docs, but for now, you can reference a temporary version here: https://gene-normalizer--209.org.readthedocs.build/en/209/quick_install.html. If you have more issues with the gene normalizer, feel free to ping us on Slack or raise them as new issues on the repo: https://github.com/cancervariants/gene-normalization.

**Comment by samriddhi99** [comment]
Hi, thank you very much for your help!
